# Generated by Django 5.1.1 on 2024-10-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paddle_billing', '0003_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='default',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='next_billed_at',
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
